# 01. Знакомство с `torch.Tensor`

---

При решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использование функционала библиотеки `torch`.

[PyTorch documentation](https://pytorch.org/docs/stable/#pytorch-documentation)

In [101]:
#Используемые библиотеки
import torch
from torch.nn import functional
from scipy.spatial import distance
from matplotlib import pyplot as plt

import warnings
warnings.filterwarnings('ignore')

## 1.1 Создание тензоров и выполнение базовых операций над ними

[Документация по функциям для создания тензоров](https://pytorch.org/docs/stable/torch.html#creation-ops)

[Документация по функциям для работы с индексами](https://pytorch.org/docs/stable/torch.html#indexing-slicing-joining-mutating-ops)

1.1.1 Создайте двумерный тензор размера (8, 8). Используя как можно меньше операций, добейтесь расстановки кодов "шахматных фигур".

Ожидаемый результат:

```
[[-4., -3., -2., -6., -5., -2., -3., -4.],
 [-1., -1., -1., -1., -1., -1., -1., -1.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [1., 1., 1., 1., 1., 1., 1., 1.],
 [4., 3., 2., 6., 5., 2., 3., 4.]]

```

In [4]:
t = torch.zeros((8, 8)) #задаем тензор размерности 8 на 8 с нулями
pawn = torch.ones((1, 8)) #пешки - единички
not_pawn = torch.arange(2, 7, 1) #не пешки - различные фигуры от 2 до 6
t[-2] = pawn #заполняем предпоследнюю строку пешками
t[-1, :3] = not_pawn[:3].sort(descending=True)[0] #заполняем первые три эл-та в последней строке отсортированными 2, 3, 4
t[-1, 5:] = not_pawn[:3].sort()[0] #заполняем последние три эл-та в последней строке отсортированными 2, 3, 4
t[-1, 3:5] = not_pawn[3:].sort(descending=True)[0] #заполняем средние элементы 6 и 5
t[:2] -= t[-2:].flip(0) #зеркалим это на верзнюю часть тензора
t #итого

tensor([[-4., -3., -2., -6., -5., -2., -3., -4.],
        [-1., -1., -1., -1., -1., -1., -1., -1.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 4.,  3.,  2.,  6.,  5.,  2.,  3.,  4.]])

1.1.2 Средствами `torch` рассчитать произведения четных чисел от 2 до 20 на ближайшие к ним бОльшие нечетные числа.

In [5]:
even_numb = torch.arange(2, 21, step=2) #берем тензор от 2 до 20
result = even_numb * (even_numb + 1) #умножаем каждое четное на рядом стоящее справа нечетное
result

tensor([  6,  20,  42,  72, 110, 156, 210, 272, 342, 420])

1.1.3 Создать тензор размера 11x7 вида: [[1, 2, 3, ..., 7], [11, 12, 13, ..., 17], [21, 22, 23, ..., 27], ..., [101, 102, 103, ..., 107]]

In [6]:
tens = torch.arange(0, 101, step=10).reshape(-1, 1) #задаем десятки от 0 до 100
units = torch.arange(1, 8) #задаем единицы от 1 до 7
result = tens + units #складываем единицы и десятки
result

tensor([[  1,   2,   3,   4,   5,   6,   7],
        [ 11,  12,  13,  14,  15,  16,  17],
        [ 21,  22,  23,  24,  25,  26,  27],
        [ 31,  32,  33,  34,  35,  36,  37],
        [ 41,  42,  43,  44,  45,  46,  47],
        [ 51,  52,  53,  54,  55,  56,  57],
        [ 61,  62,  63,  64,  65,  66,  67],
        [ 71,  72,  73,  74,  75,  76,  77],
        [ 81,  82,  83,  84,  85,  86,  87],
        [ 91,  92,  93,  94,  95,  96,  97],
        [101, 102, 103, 104, 105, 106, 107]])

1.1.4 Написать функцию, которая для целых значений `n` и `m` будет возвращать тензор размера `n`x`m`, заполненный текстурой размера 2x2, состоящей из следующих значений:

```
0 1

2 3

```

Пример для n = 4 и m = 5:

```
0 1 0 1 0

2 3 2 3 2

0 1 0 1 0

2 3 2 3 2
```

In [7]:
def filling_texture(n: int, m: int) -> torch.Tensor:
    rep = torch.tensor([[0, 1], [2, 3]]) #конструкция, которая будет повторться
    return rep.repeat(n, m)[:n, :m] #повторяет конструкцию вдоль заданных размерностей, обрезаем по необходимое нам количество

In [8]:
filling_texture(4, 5)

tensor([[0, 1, 0, 1, 0],
        [2, 3, 2, 3, 2],
        [0, 1, 0, 1, 0],
        [2, 3, 2, 3, 2]])

1.1.5 Сгенерировать двумерный тензор `t` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в дипазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида $ax+b$ так, что после нормализации максимальный элемент масива будет равен 1.0, минимальный 0.0

In [9]:
t = torch.Tensor
t = torch.empty(4, 7).uniform_(0, 20) #генерируем тензор из случайных действительных равн.распр. чисел
t

tensor([[ 9.9629,  9.9688, 17.0343,  8.0765,  3.4820,  4.3170,  1.3933],
        [ 6.9464, 19.3550,  6.6567,  3.2923,  0.7401,  0.5051, 16.6031],
        [11.6096,  1.5761,  7.9130, 19.7442,  5.2277, 14.7087, 11.0919],
        [18.1492,  2.0974,  4.5691,  9.3791,  3.1859, 12.0660, 19.0707]])

In [10]:
# это наше максмин преобразование
(t - t.min()) / (t.max() - t.min())

tensor([[0.4916, 0.4919, 0.8591, 0.3935, 0.1547, 0.1981, 0.0462],
        [0.3348, 0.9798, 0.3197, 0.1449, 0.0122, 0.0000, 0.8367],
        [0.5772, 0.0557, 0.3850, 1.0000, 0.2455, 0.7383, 0.5503],
        [0.9171, 0.0828, 0.2112, 0.4612, 0.1393, 0.6009, 0.9650]])

[Random Sampling](https://pytorch.org/docs/stable/torch.html#random-sampling)

[Distributions](https://pytorch.org/docs/stable/distributions.html)

1.1.6 Задать два двумерных тензора `ar1` и `ar2` размерности (4, 7), состоящих из случайных целых чисел в пределах от 0 до 10. Построить двумерный тензор размерности (4, 7), каждый элемент которого представляет собой максимум из двух значений, находящихся на аналогичной позиции в массивах `ar1`, `ar2`.

[Reductions ops](https://pytorch.org/docs/stable/torch.html#reduction-ops)

In [11]:
ar1 = torch.randint(0, 10, (4, 7)) #задаем 2 двумерных тензора с цел.числами от 0 до 10
ar2 = torch.randint(0, 10, (4, 7))

In [12]:
ar1

tensor([[5, 6, 4, 6, 9, 6, 2],
        [5, 3, 2, 9, 2, 9, 9],
        [7, 8, 3, 3, 0, 9, 7],
        [5, 9, 6, 6, 7, 5, 0]])

In [13]:
ar2

tensor([[0, 4, 4, 2, 6, 1, 7],
        [3, 3, 2, 0, 4, 2, 9],
        [3, 8, 5, 2, 4, 0, 4],
        [2, 5, 6, 8, 1, 0, 0]])

In [14]:
result = torch.max(ar1, ar2) #попарно сравнивает и выбирает максимальное из двух значений
result

tensor([[5, 6, 4, 6, 9, 6, 7],
        [5, 3, 2, 9, 4, 9, 9],
        [7, 8, 5, 3, 4, 9, 7],
        [5, 9, 6, 8, 7, 5, 0]])

1.1.7 Создать тензор из 20 случайных целых чисел от 0 до 100. Получить второе сверху значение в тензоре. Определить индекс этого значения.

In [15]:
t20 = torch.randint(0, 100, size=(20, )) #генерируем тензор
t20

tensor([19,  9, 11, 94, 45, 50, 57, 87, 95, 10, 64, 36,  0, 79, 40, 78, 98, 40,
        83,  2])

In [19]:
#Определяем индекс нужного значения
max2 = t20.argsort()[-2] #сортируем и берем предпоследнее значение
max2

tensor(8)

In [20]:
#берем само это значение
result = t20[max2]
result

tensor(95)

## 1.2 Распространение

[Numpy broadcasting](https://numpy.org/devdocs/user/theory.broadcasting.html)

[Torch broadcasting](https://pytorch.org/docs/stable/notes/broadcasting.html)

1.2.1 Создать тензор 11x7 вида: `[[1, 2, 3, ..., 7], [11, 12, 13, ..., 17], [21, 22, 23, ..., 27], ..., [101, 102, 103, ..., 107]]`. При решении задачи применить технику распространения.

In [21]:
tens = torch.arange(0, 101, step=10).reshape(-1, 1) # десятки по столбцам
units = torch.arange(1, 8) #единицы
result = tens + units #складываем десятки и единицы
result

tensor([[  1,   2,   3,   4,   5,   6,   7],
        [ 11,  12,  13,  14,  15,  16,  17],
        [ 21,  22,  23,  24,  25,  26,  27],
        [ 31,  32,  33,  34,  35,  36,  37],
        [ 41,  42,  43,  44,  45,  46,  47],
        [ 51,  52,  53,  54,  55,  56,  57],
        [ 61,  62,  63,  64,  65,  66,  67],
        [ 71,  72,  73,  74,  75,  76,  77],
        [ 81,  82,  83,  84,  85,  86,  87],
        [ 91,  92,  93,  94,  95,  96,  97],
        [101, 102, 103, 104, 105, 106, 107]])

1.2.2 Вычесть одномерный тензор `b_1d` из двухмерного тензора `a_2d`, так, чтобы каждый элемент одномерного тензора вычитался из всех элементов соответствующих строк двумерного тензора.

_Пример:_

Для входа:
```python
a_2d = np.array([[3,3,3],[4,4,4],[5,5,5]])
b_1d = np.array([1,2,3])
```

Ожидается резульат:

```python
[[2 2 2]
 [2 2 2]
 [2 2 2]]
```

In [28]:
def broadcast_subtraction(t1: torch.Tensor, t2: torch.Tensor) -> torch.Tensor:
    #меняем его размер с (1, 3) на (3, 1), то есть меняем кол-во строк и столбцов 
    return t1 - t2.reshape(-1, 1) #и вычитаем из первого

In [29]:
a_2d = torch.tensor([[3, 3, 3], [4, 4, 4], [5, 5, 5]])
b_1d = torch.tensor([1, 2, 3])
broadcast_subtraction(a_2d, b_1d)

tensor([[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]])

## 1.3 Индексы, маскирование и прихотливое индексирование

[Документация по функциям для работы с индексами](https://pytorch.org/docs/stable/torch.html#indexing-slicing-joining-mutating-ops)

1.3.1 Получить индексы, для которых элементы тензоров `a` и `b` совпадают.

_Пример:_

Для входа:
```python
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```

Ожидается резульат:

```python
array([1, 3, 5, 7])
```

In [30]:
def same_element(t1: torch.Tensor, t2: torch.Tensor) -> torch.Tensor:
    return (t1 == t2).nonzero(as_tuple=True)[0] #вернет кортеж (точнее его 0 эл-т) списка индексов True объектов

In [31]:
a = torch.tensor([1, 2, 3, 2, 3, 4, 3, 4, 5, 6]) # задаем тензоры
b = torch.tensor([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])

same_element(a, b)

tensor([1, 3, 5, 7])

1.3.2 Инвертировать порядок элементов в двумерном тензоре `torch.arange(9).view(3,3)`.

Ожидаемый результат:


```python
array([[8, 7, 6],
       [5, 4, 3],
       [2, 1, 0]])
```

In [32]:
t = torch.arange(9).view(3,3) #задаем тензор
t

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [33]:
t.flip([0, 1]) #меняем порядок вдоль заданной оси, в данном случае и строка, и столбец

tensor([[8, 7, 6],
        [5, 4, 3],
        [2, 1, 0]])

1.3.3 Из входного тензора a получить только элементы, находящиеся в диапазоне от 5 до 10.

_Пример:_

Для входа:
```python
a = np.array([2, 6, 1, 9, 10, 3, 27])
```

Ожидается резульат:

```python
array([6, 9, 10])
```

In [34]:
def more_than_ten(t: torch.Tensor) -> torch.Tensor:
    return t[(t >=5) & (t <= 10)] #возвращаем элементы из указанного диапазона

In [35]:
a = torch.tensor([2, 6, 1, 9, 10, 3, 27])
more_than_ten(a)

tensor([ 6,  9, 10])

In [36]:
a = torch.tensor([10, 12, 5])
more_than_ten(a)

tensor([10,  5])

1.3.4 Поменять местами столбец 1 и 2 тензора `np.arange(9).reshape(3,3)`

In [37]:
t = torch.arange(9).reshape(3, 3)
t

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [38]:
t[:, [0, 1]] = t[:, [1, 0]] #явно меняем местами с помощью значений по индексу
t

tensor([[1, 0, 2],
        [4, 3, 5],
        [7, 6, 8]])

1.3.5 Создать тензор 8 на 10 из случайных целых чисел из диапазона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [ ]:
t = torch.randint(0, 11, size=(8, 10))
t

In [ ]:
i = t.sum(1).argmin() #находим сначала суммы по строке, затем индекс минимума из них с помощью argmin
s = t[i]
print(f'Строка с минимальной суммой: {s}, \nИндекс строки: {i}')

1.3.6 Cоздать тензор из 20 случайных целых чисел от 0 до 100. Обрезать значения тензора (заменить значения, выходящие за диапазон, на крайние значения) снизу по значению 30, сверху по значению 70.

In [39]:
t = torch.randint(0, 101, size=(20, ))
t

tensor([29, 66,  3, 93, 41, 46, 89, 92, 78, 16, 77,  3,  8, 55,  2, 47, 64, 93,
        59, 43])

In [40]:
torch.clamp(t, min=30, max=70) #если значение меньше 30, то подставляется 30, если больше 70, то - 70

tensor([30, 66, 30, 70, 41, 46, 70, 70, 70, 30, 70, 30, 30, 55, 30, 47, 64, 70,
        59, 43])

1.3.7 Создать два тензора размера 30 на 3 из случайных целых чисел из диапазона от 0 до 10 и найти все значения первого тензора, которые больше соответсвующих (по расположению) значений второго тензора. Подсчитать сумму этих значений.

In [41]:
t1 = torch.randint(0, 11, size=(30, 3))
t1

tensor([[ 2,  0,  2],
        [ 0,  1,  4],
        [ 5, 10,  7],
        [ 1, 10,  4],
        [ 2,  1,  6],
        [ 8,  9,  6],
        [ 1,  0,  3],
        [ 0,  5, 10],
        [ 2,  1,  6],
        [ 2, 10,  1],
        [ 1,  9, 10],
        [10,  7,  8],
        [ 3,  0,  4],
        [ 8,  8,  3],
        [ 5,  0,  9],
        [ 4,  3,  8],
        [ 2,  9,  4],
        [ 3,  7,  9],
        [ 6,  8,  8],
        [10,  7,  5],
        [ 2,  0,  5],
        [ 2,  5,  9],
        [ 9,  7,  8],
        [ 9,  0,  4],
        [ 9,  7,  6],
        [10,  9,  3],
        [ 8,  7,  3],
        [ 7,  3,  5],
        [ 5,  4,  2],
        [ 5,  7,  5]])

In [42]:
t2 = torch.randint(0, 11, size = (30, 3))
t2

tensor([[ 7,  8,  7],
        [ 8,  3,  9],
        [ 7,  1,  5],
        [ 8,  5,  1],
        [ 9,  6, 10],
        [ 6,  7,  3],
        [ 8,  9,  6],
        [ 3,  4,  1],
        [ 2,  4,  1],
        [10,  4,  6],
        [ 4,  4,  4],
        [ 6,  3,  7],
        [ 8,  9,  5],
        [ 1, 10,  6],
        [10,  8,  6],
        [ 5,  8,  5],
        [ 8,  8,  5],
        [ 9,  7,  7],
        [ 8,  4,  1],
        [ 5,  4,  2],
        [10,  8,  0],
        [ 6,  6,  9],
        [ 7,  0,  7],
        [ 7,  9,  3],
        [ 5,  2,  6],
        [ 3,  8,  0],
        [ 1,  4,  7],
        [ 4,  3,  4],
        [ 9,  0,  7],
        [ 3,  8,  6]])

In [43]:
t1>t2 #маска, по которой будет считаться сумма

tensor([[False, False, False],
        [False, False, False],
        [False,  True,  True],
        [False,  True,  True],
        [False, False, False],
        [ True,  True,  True],
        [False, False, False],
        [False,  True,  True],
        [False, False,  True],
        [False,  True, False],
        [False,  True,  True],
        [ True,  True,  True],
        [False, False, False],
        [ True, False, False],
        [False, False,  True],
        [False, False,  True],
        [False,  True, False],
        [False, False,  True],
        [False,  True,  True],
        [ True,  True,  True],
        [False, False,  True],
        [False, False, False],
        [ True,  True,  True],
        [ True, False,  True],
        [ True,  True, False],
        [ True,  True,  True],
        [ True,  True, False],
        [ True, False,  True],
        [False,  True, False],
        [ True, False, False]])

In [44]:
t1[t1>t2].sum()

tensor(326)

1.3.8 При помощи прихотливого индексирования для двухмерного массива размерности (20, 20), состоящего из случайных целых чисел в пределах от 0 до 10 получить массив элементов находящихся на диагонали, проходящей над основной диагональю.

In [45]:
t = torch.randint(0, 11, size=(20, 20))
t

tensor([[ 2, 10,  3, 10, 10,  5, 10, 10,  4,  0,  2,  6,  4,  9,  3,  7,  8,  9,
          5,  9],
        [ 3,  7,  4,  4,  3,  5,  5,  4,  9, 10,  8, 10,  0,  8,  7,  4,  0,  5,
          1,  4],
        [ 5,  2,  5, 10, 10,  5,  6,  9,  0,  7,  7,  1,  5,  7,  2,  3,  5,  4,
          0,  1],
        [ 6,  8, 10,  5,  8,  5,  9,  6,  6,  3,  5,  1,  4,  2,  5,  3,  1,  6,
          6,  2],
        [ 1,  4,  2,  3,  5,  4,  4,  4,  1,  9,  6,  1,  8,  8,  2,  8,  8,  3,
         10,  4],
        [ 0, 10, 10,  9,  0,  2,  9,  6,  3,  8,  9,  7,  7,  4,  8, 10,  2,  2,
          7,  5],
        [ 4,  2, 10,  1,  7,  2,  0,  5, 10, 10,  3,  6, 10,  4,  7, 10,  0,  9,
          7,  3],
        [ 8,  0,  1,  9,  8,  3,  2,  1,  2,  4,  8,  3,  6,  3,  1,  7, 10,  1,
          1,  9],
        [ 1,  0,  7,  7,  6,  6,  2,  6,  0,  6,  7,  6, 10,  4,  8,  9,  4,  2,
          8,  5],
        [ 8,  3, 10,  3,  3,  8,  0,  3,  0,  3,  7,  7,  9,  2, 10, 10,  0, 10,
          3,  2],
        [1

In [46]:
t[torch.arange(0, t.shape[0] - 1), torch.arange(1, t.shape[0])] #то есть берем парами строка-столбец и сдвигаем их на 1 попарно
#то есть мы берем сначала 0 строка и 1 столб., затем 1 строка и 2 столб. и т.д.

tensor([10,  4, 10,  8,  4,  9,  5,  2,  6,  7,  5,  7,  8, 10,  6, 10,  1,  7,
         8])

1.3.9 Задать два двухмерных тензора `ar1` и `ar2` размерности (5, 10), состоящих из случайных целых чисел в пределах от 0 до 10. Удвоить все значения `ar1`, которые совпадают со значениями `ar2`, расположенными на аналогичных позициях.

In [47]:
ar1 = torch.randint(0, 11, size=(5, 10))
ar1

tensor([[ 2,  0,  1,  9,  1,  6,  0,  0, 10,  6],
        [ 5, 10, 10,  0,  0,  2,  3,  8,  5,  3],
        [10,  5,  6,  2,  7,  1,  3, 10,  9,  1],
        [ 1,  8,  6,  5,  8,  5,  7,  7,  1,  1],
        [ 2,  0,  8,  9,  2,  6,  7,  3,  8,  4]])

In [48]:
ar2 = torch.randint(0, 11, size=(5, 10))
ar2

tensor([[ 4,  8,  5,  0,  6,  6,  9,  9, 10,  0],
        [ 9,  9,  1,  5,  5,  9,  3,  6,  9,  2],
        [10,  7,  2,  8,  2,  8,  4,  5,  5,  6],
        [ 0, 10,  0,  3,  5,  7,  1,  1, 10,  5],
        [ 0,  7, 10,  5,  0,  8,  1,  3, 10,  4]])

In [49]:
ar1[ar1==ar2] *= 2 #если значение совпадает, то удваиваем
ar1

tensor([[ 2,  0,  1,  9,  1, 12,  0,  0, 20,  6],
        [ 5, 10, 10,  0,  0,  2,  6,  8,  5,  3],
        [20,  5,  6,  2,  7,  1,  3, 10,  9,  1],
        [ 1,  8,  6,  5,  8,  5,  7,  7,  1,  1],
        [ 2,  0,  8,  9,  2,  6,  7,  6,  8,  8]])

1.3.10 Заданы три двухмерных тензора `ar1`, `ar2` и `ar3` размерности (4, 7), состоящие из случайных целых чисел в пределах от 0 до 10. Обнулить все элементы `ar1`, которые больше соответствующих (находящихся в соответствующих позициях) элементов `ar2` и меньше соответствующих элементов `ar3`.

In [50]:
ar1 = torch.randint(0, 11, size=(4, 7))
ar1

tensor([[ 5,  0,  6,  1,  5,  5, 10],
        [ 8,  6,  5,  4,  6,  9,  3],
        [ 5,  8,  3,  0, 10,  4, 10],
        [ 8,  9,  0,  1,  8,  5,  2]])

In [51]:
ar2 = torch.randint(0, 11, size=(4, 7))
ar2

tensor([[ 7,  7,  7,  3,  8,  6,  9],
        [ 7,  8,  4, 10,  0,  5,  1],
        [ 4,  2,  6,  8,  6,  3,  3],
        [ 4, 10, 10,  1,  2,  1,  5]])

In [52]:
ar3 = torch.randint(0, 11, size=(4, 7))
ar3

tensor([[ 3,  7,  7,  9,  2, 10, 10],
        [ 4,  2,  3,  5,  1,  8,  0],
        [ 1,  1,  0,  0,  3,  7,  7],
        [ 4,  9,  6, 10,  6,  8,  3]])

In [53]:
ar1[(ar1>ar2) & (ar1<ar3)] = 0 #согласно условию (больше, чем во втором, но меньше, чем в третьем) обнуляем
ar1

tensor([[ 5,  0,  6,  1,  5,  5, 10],
        [ 8,  6,  5,  4,  6,  9,  3],
        [ 5,  8,  3,  0, 10,  0, 10],
        [ 8,  9,  0,  1,  8,  0,  2]])

1.3.11 Задан двумерный тензор `ar1` размерности (20, 5), состоящий из случайных целых чисел в пределах от 0 до 20. Определить, в каких столбцах не менее 5 раз встречается значение, максимальное по своей строке.

In [54]:
ar1 = torch.randint(0, 21, size=(20, 5)) #генерируем тензор
ar1

tensor([[16,  0, 19, 15, 19],
        [ 8,  2,  7,  4,  2],
        [10,  9,  8,  6, 10],
        [ 2,  9,  6,  8, 18],
        [ 6, 14, 19, 20,  2],
        [ 1,  3,  5, 11,  7],
        [12, 20, 11,  2,  1],
        [ 4, 11, 10,  6, 19],
        [14, 19, 12, 17, 13],
        [ 1,  1,  2, 16,  6],
        [16,  7, 11, 17, 12],
        [10, 16,  6,  6, 10],
        [20, 16, 11,  3,  7],
        [ 5,  7, 13, 17, 20],
        [20,  5, 20,  1, 15],
        [ 3,  0, 20,  6, 12],
        [ 0,  5, 11,  8,  3],
        [10,  4, 12, 17,  7],
        [16, 17, 15, 15,  9],
        [ 3,  6, 14, 19,  6]])

In [55]:
max_inds = ar1.argmax(1) #берем индексы максимальных значений в каждой строке
max_inds

tensor([2, 0, 0, 4, 3, 3, 1, 4, 1, 3, 3, 1, 0, 4, 0, 2, 2, 3, 1, 3])

In [56]:
i, n = max_inds.unique(return_counts=True) #составляем пары сколько раз каждый индек встречался

In [57]:
i[n >= 5] # определяем, в каких столбцах не менее 5 раз встречается значение, максимальное по своей строке

tensor([3])

1.3.12 Задан двумерный тензор `ar1` размерности (4, 7), состоящий из случайных  чисел в пределах от 0 до 1. Обнулить все значения в массиве, расположенные строго правее и ниже максимального элемента массива. 

In [58]:
ar1 = torch.rand(4, 7) #генерируем тензор с числами от 0 до 1
ar1

tensor([[0.3546, 0.3814, 0.4680, 0.5804, 0.4665, 0.1247, 0.5216],
        [0.9694, 0.3433, 0.0401, 0.4519, 0.7936, 0.1168, 0.8644],
        [0.5195, 0.2105, 0.0925, 0.1681, 0.3505, 0.9217, 0.3702],
        [0.9604, 0.6535, 0.9669, 0.7492, 0.4546, 0.5759, 0.6183]])

In [60]:
ar1.max(), ar1.argmax()  #берем максимальное число и его индекс

(tensor(0.9694), tensor(7))

In [64]:
i = ar1.argmax() // ar1.shape[1] #Находим строку (делим максимальный индекс на количество столбцов нацело)
j = ar1.argmax() % ar1.shape[1] #находим столбец (находим остаток от деления у максимального индекса на количество столбцов) 
ar1[i + 1:, j + 1:] = 0 #ниже этой строки и правее этого столбца обнуляем
ar1

tensor([[0.3546, 0.3814, 0.4680, 0.5804, 0.4665, 0.1247, 0.5216],
        [0.9694, 0.3433, 0.0401, 0.4519, 0.7936, 0.1168, 0.8644],
        [0.5195, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.9604, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000]])

1.3.13 Построить "one-hot encoding" для одномерного тензора, содержащего целые числа (длина вектора заранее неизвестна, набор значений заранее неизвестен, при этом в итоговой матрице должны присутствовать столбцы для всех натуральных чисел вплоть до максимального встречающегося в исходном массиве).

Пример:

для тензора `torch.tensor([2, 3, 2, 2, 2, 1])`.

Ожидается результат:

```python
tensor([[0., 1., 0.],
        [0., 0., 1.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [1., 0., 0.]])
```

In [65]:
def one_hot_enc(t: torch.Tensor) -> torch.Tensor:
    return functional.one_hot(t-1) #если не -1, то он добавляет столбец с идеальным 0, куда будет стремиться

In [66]:
t = torch.tensor([2, 3, 2, 2, 2, 1])
one_hot_enc(t)

tensor([[0, 1, 0],
        [0, 0, 1],
        [0, 1, 0],
        [0, 1, 0],
        [0, 1, 0],
        [1, 0, 0]])

1.3.14 Создать тензор `arr` из 20 случайных целых чисел от 0 до 100. Найти самое частое значение в тензоре. 
Найти индексы в тензоре, соответствующие самому частому значению. Проверить, как работет алгоритм при двух значениях, имеющих наибольшую встречаемость, предложить приемлемое поведение алгоритма для этого случая. 

In [69]:
arr = torch.randint(0, 101, size=(20, )) #задаем тензор
arr

tensor([25, 54,  3, 87, 17, 21, 20, 15, 56, 29, 37, 21, 95,  0,  1,  7, 81, 10,
        66, 99])

In [70]:
mode = torch.mode(arr)[0] #находим самое частое значение
mode

tensor(21)

In [71]:
(arr == mode).nonzero(as_tuple=True)[0] #индексы, где встречается

tensor([ 5, 11])

## 1.4 Математические задачи

1.4.1 Приблизительно (с погрешностью порядка 1%) рассчитать на какой части интервала от 0 до 10 значение функции x * sin(x) больше 0.5.

In [102]:
x = torch.linspace(0, 10, 100) #задаем значения x
y = x * torch.sin(x)
result = (y > 0.5).sum() / 100
result

tensor(0.5200)

1.4.2 Найти все простые числа в пределах ста. (Для решения предлагается использовать Решето Эратосфена) Использовать не более 1 цикла (желательно).

In [78]:
n = torch.tensor(100) #так как в пределах 100
nums = torch.arange(2, 101) #генерируем тензор всех чисел

#далее согласно правилам в Решете Эратосфена
p = 2 #первое простое число = 2
colander = torch.full(nums.size(), fill_value=True) #берем максу, где изначально все числа - простые
#Далее согласно правилам имеет смысл вычеркивать не простые числа в таблице до тех пор, пока значение p**2 < n
while p < torch.sqrt(n) + 1: #то есть пока p < 11
    colander[2 * p - 2::p] = False #берем значения кратные p (2p, 3p, 4p) отнимаем 2 и с шагом p - это не простые числа
    p = nums[colander & (nums > p)][0] #берем следующее незачеркнутое число
nums[colander] #и числа, которые остались не зачеркнутыми, выводим

tensor([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61,
        67, 71, 73, 79, 83, 89, 97])

1.4.3 Найти евклидово расстояние между двумя одномерными тензорами одинаковой размерности, не используя готовые решения из библиотек.

In [79]:
t1 = torch.tensor([1, 2, 3, 4, 5], dtype=torch.float) #задаем тензоры
t2 = torch.tensor([11, 12, 13, 14, 15], dtype=torch.float)
e_dist_1 = torch.sqrt(torch.sum((t1 - t2) ** 2)) #по формуле находим евклидово расстояние
e_dist_2 = distance.euclidean(t1, t2) #проверяем встроенной библиотекой
print(f'Евклидово расстояние без помощи билиотеки: {e_dist_1}\n'
      f'Евклидово расстояние с помощью билиотеки: {e_dist_2}')

Евклидово расстояние без помощи билиотеки: 22.360679626464844
Евклидово расстояние с помощью билиотеки: 22.360679626464844


1.4.4 Создать двумерный тензор 20 на 3, содержащий случайные целые числа от 0 до 100. 
Интерпретируя тензор как 20 векторов из 3х компонент, отсортировать его по длине векторов.

In [80]:
t = torch.randint(0, 100, size=(20, 3)) #формируем тензор
t

tensor([[13, 76, 38],
        [ 7, 66, 74],
        [75, 24, 28],
        [31, 40, 41],
        [24, 55, 62],
        [92, 20,  3],
        [26,  2, 40],
        [ 1, 24, 98],
        [35, 87, 32],
        [31, 25, 94],
        [56, 62, 73],
        [76, 68, 59],
        [47,  2, 30],
        [ 7, 46, 79],
        [53, 12, 53],
        [30, 78, 41],
        [83,  6, 56],
        [83, 41, 47],
        [ 6, 54, 40],
        [45, 42, 59]])

In [81]:
t[torch.sqrt((t**2).sum(1)).argsort()] #Длина вектора - корень из суммы квадратов координат

tensor([[26,  2, 40],
        [47,  2, 30],
        [31, 40, 41],
        [ 6, 54, 40],
        [53, 12, 53],
        [75, 24, 28],
        [45, 42, 59],
        [13, 76, 38],
        [24, 55, 62],
        [ 7, 46, 79],
        [30, 78, 41],
        [92, 20,  3],
        [35, 87, 32],
        [ 7, 66, 74],
        [83,  6, 56],
        [ 1, 24, 98],
        [31, 25, 94],
        [83, 41, 47],
        [56, 62, 73],
        [76, 68, 59]])

1.4.5 Найти "локальные максимумы" в одномерном тензоре (т.е. значения, большие предыдущего и последующего) `torch.tensor([1, 3, 7, 1, 2, 6, 0, 1])` и вывести их индексы.

In [83]:
t = torch.tensor([1, 3, 7, 1, 2, 6, 0, 1])
r = torch.roll(t, -1) #сворачиваем до [3, 7, 1, 2, 6, 0, 1, 1], подвинуть влево на одну, т.е. берем все правые
l = torch.roll(t, 1) #сворачиваем до [1, 1, 3, 7, 1, 2, 6, 0], подвинуть вправо на одну, т.е. берем все левые

cond = (t > l) & (t > r) #лок макс по условию
#края считаем отдельно:
cond[0] = t[0] > t[1] #левый край
cond[-1] = t[-1] > t[-2] #правый край

inds = cond.nonzero(as_tuple=True) #индексы
print(f'Значения Локальных максимумов: {t[inds]}\nИх индексы: {inds[0]}"')

Значения Локальных максимумов: tensor([7, 6, 1])
Их индексы: tensor([2, 5, 7])"


1.4.6 Задан произвольный массив numpy (например массив из 100 случайных числе от 0 до 1). Необходимо найти в нем число наиболее близкое к заданному.

In [89]:
def find_number(t: torch.Tensor, n: float):
    #то есть будем смотреть минимаальную разность между числами по модулю
    print(f'Задано число: {n}\nБлижайшее к заданному числу: {t[(t-n).abs().argmin()]}\nИндекс ближайшего числа: {(t-n).abs().argmin()}')

In [90]:
t = torch.rand(100, )
find_number(t, 0.6)

Задано число: 0.6
Ближайшее к заданному числу: 0.5907866954803467
Индекс ближайшего числа: 47


In [91]:
find_number(t, 0.01)

Задано число: 0.01
Ближайшее к заданному числу: 0.006974458694458008
Индекс ближайшего числа: 88


In [92]:
find_number(t, 0.9)

Задано число: 0.9
Ближайшее к заданному числу: 0.8970754146575928
Индекс ближайшего числа: 36


In [93]:
find_number(t, 1)

Задано число: 1
Ближайшее к заданному числу: 0.999396562576294
Индекс ближайшего числа: 26


1.4.7 Решить матричное уравнение `A*X*B=-C` - найти матрицу X. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [94]:
A = torch.tensor([[-1, 2, 4],[-3, 1, 2],[-3, 0, 1],], dtype=torch.float)
B = torch.tensor([[3, -1],[2, 1],], dtype=torch.float)
C = torch.tensor([[7, 21],[11, 8],[8, 4],], dtype=torch.float)

# torch.inverse - вычисление обратной матрицы
# torch.matmul - вычисление матричного произведения
# Нам надо найти -A * -C * -B
X = torch.matmul(torch.matmul(torch.inverse(A), -C), torch.inverse(B))
X

tensor([[ 1.0000e+00,  5.9605e-08],
        [-2.0000e+00,  1.0000e+00],
        [ 3.0000e+00, -4.0000e+00]])

1.4.8 Проверить, является ли система векторов a1 = (3; −3; 0; 7),
a2 = (2; 2; 4; 7), a3 = (1; 2; 3; 4), a4 = (5; −4; 1; 3) линейно зависимой?

In [95]:
a1 = torch.tensor([3, -3, 0, 7], dtype=torch.float) #задаем тензоры
a2 = torch.tensor([2, 2, 4, 7], dtype=torch.float)
a3 = torch.tensor([1, 2, 3, 4], dtype=torch.float)
a4 = torch.tensor([5, -4, 1, 3], dtype=torch.float)

In [96]:
m = torch.vstack([a1, a2, a3, a4]) #объединим по вертикали
m

tensor([[ 3., -3.,  0.,  7.],
        [ 2.,  2.,  4.,  7.],
        [ 1.,  2.,  3.,  4.],
        [ 5., -4.,  1.,  3.]])

In [98]:
if torch.linalg.matrix_rank(m) == m.shape[0]: #если ранг матрицы совпадает с количеством векторов, то линейно независимая
    print("Система векторов является линейно независимой.")
else:
    print("Система векторов не является линейно независимой.")

Система векторов не является линейно независимой.


1.4.9 Сгенирировать тензор из 200 случайных целых чисел, нормально распрделенных cо стандартным отклонением $\sigma = 10$ и матожиданием $\mu = 0$. Построить тензор гистограммы с 20 бинами. 

In [99]:
t = torch.normal(mean=0, std=10, size=(200,)) #Задаем тензор с условиями задания
torch.histogram(t, bins=20) #строим, указам бины

torch.return_types.histogram(
hist=tensor([ 3.,  1.,  3.,  6.,  5., 17., 13., 11., 20., 24., 26., 14., 12., 17.,
         8.,  9.,  5.,  3.,  1.,  2.]),
bin_edges=tensor([-24.5768, -22.0740, -19.5712, -17.0684, -14.5655, -12.0627,  -9.5599,
         -7.0571,  -4.5543,  -2.0515,   0.4514,   2.9542,   5.4570,   7.9598,
         10.4626,  12.9654,  15.4682,  17.9711,  20.4739,  22.9767,  25.4795]))

In [100]:
# Если только гистограмму, то можно использовать это, min и max по умолчанию 0, чтоб использовались max и min из данных
torch.histc(t, bins=20)

tensor([ 3.,  1.,  3.,  6.,  5., 17., 13., 11., 20., 24., 26., 14., 12., 17.,
         8.,  9.,  5.,  3.,  1.,  2.])